// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoForm_Externe.Data;

#nullable disable

namespace NeoForm_Externe.Migrations
{
    [DbContext(typeof(ExternalNeoFormContext))]
    partial class ExternalNeoFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NeoForm_Externe.Models.ClientInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Clients", "AppNeoForm");
                });

            modelBuilder.Entity("NeoForm_Externe.Models.ObjectModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Application")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("application")
                        .HasComputedColumnSql("(left(json_value([ObjectJson],'$.application'),(100)))", false);

                    b.Property<string>("Guid")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("guid")
                        .HasComputedColumnSql("(left(json_value([ObjectJson],'$.guid'),(100)))", false);

                    b.Property<bool>("IsEncrypted")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasColumnName("isEncrypted")
                        .HasComputedColumnSql("CASE WHEN JSON_VALUE([ObjectJson], '$.isEncrypted') = 'true' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END", false);

                    b.Property<string>("ObjectJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("objectName")
                        .HasComputedColumnSql("(left(json_value([ObjectJson],'$.objectName'),(100)))", false);

                    b.Property<string>("ObjectType")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("objectType")
                        .HasComputedColumnSql("(left(json_value([ObjectJson],'$.objectType'),(100)))", false);

                    b.HasKey("Id")
                        .HasName("PK_Object");

                    b.ToTable("Object", "AppNeoForm");
                });
#pragma warning restore 612, 618
        }
    }
}
